version: '3'
services:
  roads_postgres:
    container_name: roads_postgres
    image: "postgres:14-alpine"
    env_file:
      - dev.env
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - roads_net
    logging:
      driver: none
  roads:
    container_name: roads
    image: roads_admin_roads:latest
    env_file:
      - dev.env
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      - roads_net
    depends_on:
      - roads_postgres
networks:
  roads_net:
    driver: bridge
