version: '3'
services:
  roads_postgres:
    container_name: roads_postgres
    image: "postgres:14-alpine"
    env_file:
      - dev.env
    ports:
      - "127.0.0.1:5432:5432"
    logging:
      driver: none
